name: 'Push Alert'
description: 'Send a Slack alert when an unreviewed commit is pushed to master'
author: 'Shiqi Yang'
inputs:
  repo-token:
    description: 'Token for the repo. Can be passed in using {{ secrets.GITHUB_TOKEN }}.'
    required: true
  slack-endpoint:
    description: 'Slack notification endpoint. Can be passed in using {{ secrets.SLACK_NOTIFY_ENDPOINT }}.'
    required: true
  slack-channel:
    description: 'Slack channel name to notify.'
    required: true
runs:
  using: 'node24'
  main: 'dist/index.js'